const RECEIVE_WEB_SOCKET_CONNECTION = 'RECEIVE_WEB_SOCKET_CONNECTION';

const RECEIVE_STATE = 'RECEIVE_STATE';

const RESET_STATE = 'RESET_STATE';

export {
    RECEIVE_WEB_SOCKET_CONNECTION,
    RECEIVE_STATE,
    RESET_STATE,
};
